### ISSUE TITLE
Error when using wavelet.

### ISSUE THREAD

**Issue by Danottonove** [kmaterna/Strain_2D#37]
Hi,
Good job!!! 
I use the wavelet method but I get an error message!
 I set the parameters and launch strain_rate_compute.py, then launch the matlab code using the parameters and instructions provided by Strain_2D in the output folder. Having obtained the Matlab outputs, I return to python and enter the path but get the following error message: 

Writing 2d outputs:
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\anaconda3\envs\Strain_2D\Scripts\strain_rate_compute.py", line 11, in <module>
    internal_coordinator.strain_coordinator(MyParams)
  File "C:\Users\XXXX\AppData\Local\anaconda3\envs\Strain_2D\Lib\site-packages\strain\internal_coordinator.py", line 27, in strain_coordinator
    output_manager.outputs_2d(Ve, Vn, rot, exx, exy, eyy, MyParams, vels, resids)  # 2D grid output format
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\anaconda3\envs\Strain_2D\Lib\site-packages\strain\output_manager.py", line 14, in outputs_2d
    raise ValueError("Error! Velocity field and residual field have different lengths.")
ValueError: Error! Velocity field and residual field have different lengths.

Can you tell me the reason why? thank you all

**Comment by jlmaurer** [comment]
@Danottonove I have a PR in the works right now that addresses this issue. @kmaterna #41 is this same issue.
