### ISSUE TITLE
gpsgridder error

### ISSUE THREAD

**Issue by odito2** [kmaterna/Strain_2D#39]
Hi again, I received an error for strain calculation with gpsgridder. My files are attached and so is the message error. I'll be happy for your advice. Thanks!

[strain_config_gpsgridder_Isr.txt](https://github.com/kmaterna/Strain_2D/files/14948806/strain_config_gpsgridder_Isr.txt)
[StrainTensor_input.txt](https://github.com/kmaterna/Strain_2D/files/14948825/StrainTensor_input.txt)

D:\Ariel\Phd\Strain_software\Strain_2D\example>python ..\Strain_Tools\bin\strain_rate_compute.py strain_config_gpsgridder_Isr.txt

------------------------------
Hello! We are...
   Computing strain using : gpsgridder
   Input data from        : ../test/testing_data/StrainTensor_input.txt
   Calculation range      : [34.0, 36.1, 32.1, 33.9]
   Putting the outputs    : Output/gpsgridder/

------------------------------
Reading file ../test/testing_data/StrainTensor_input.txt
11 stations before applying cleaning.
11 stations after imposing bounding box.

------------------------------
Computing strain via gpsgridder method.
writing vector output file tempgps.txt
gmt gpsgridder tempgps.txt -R33.98/36.120000000000005/32.08/33.92 -I0.04/0.04 -S0.5 -Fd0.01 -C0.0001 -Emisfitfile.txt -fg -r -Gnc_%s.nc
gpsgridder [WARNING]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
gpsgridder (gmt_api.c:2126(gmtapi_init_grdheader)): Please select compatible -R and -I values
gpsgridder [WARNING]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
gpsgridder (gmt_api.c:2126(gmtapi_init_grdheader)): Please select compatible -R and -I values
Traceback (most recent call last):
  File "D:\Ariel\Phd\Strain_software\Strain_2D\Strain_Tools\bin\strain_rate_compute.py", line 11, in <module>
    internal_coordinator.strain_coordinator(MyParams);
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain_2d-1.1.1-py3.10.egg\strain\internal_coordinator.py", line 26, in strain_coordinator
    [Ve, Vn, rot, exx, exy, eyy, vels, resids] = constructed_object.compute(velField);  # computing strain
 File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain_2d-1.1.1-py3.10.egg\strain\models\strain_gpsgridder.py", line 24, in compute
    [Ve, Vn, rot_grd, exx_grd, exy_grd, eyy_grd] = compute_gpsgridder(myVelfield, self._strain_range,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain_2d-1.1.1-py3.10.egg\strain\models\strain_gpsgridder.py", line 66, in compute_gpsgridder
    subprocess.call(['rm', 'tempgps.txt'], shell=False);
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kmaterna** [comment]
@odito2 it may have been a problem because I copied files with subprocess instead of native python libraries like shutil (my own less-functional legacy code, sorry).  I tried to fix it with https://github.com/kmaterna/Strain_2D/commit/e466e90be0aeeba62fe75e1ca17d58761e2c5536
Any change in results?

**Comment by odito2** [comment]
Thank you so much for your answer. I just returned from a long vacation and
saw your reply. I tried to run the gpsgridder but still receive the same
error.

Odelya

‫בתאריך יום ו׳, 19 באפר׳ 2024 ב-5:42 מאת ‪kmaterna‬‏ <‪
***@***.***‬‏>:‬

**Comment by odito2** [comment]
On Windows, I get the following error:
```
'awk' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "D:\Ariel\Phd\Strain_software\Strain_2D-master\Strain_Tools\bin\strain_rate_compute.py", line 11, in <module>
    internal_coordinator.strain_coordinator(MyParams)
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\internal_coordinator.py", line 26, in strain_coordinator
    [Ve, Vn, rot, exx, exy, eyy, vels, resids] = constructed_object.compute(velField)  # computing strain
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\models\strain_gpsgridder.py", line 26, in compute
    [Ve, Vn, rot_grd, exx_grd, exy_grd, eyy_grd] = compute_gpsgridder(myVelfield, self._strain_range,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\models\strain_gpsgridder.py", line 86, in compute_gpsgridder
    xinc = float(subprocess.check_output('gmt grdinfo -M -C '+file1+' | awk \'{print $8}\'', shell=True))  # x-inc
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gmt grdinfo -M -C Output/gpsgridder/nc_u.nc | awk '{print $8}'' returned non-zero exit status 255.
```
Can you remove the dependency on awk?

Switching to Linux, delauny works, but when I try to use gpsgridder I get the following error:
```
Computing strain invariants for 2d dataset.
Traceback (most recent call last):
  File "/mnt/d/Ariel/Phd/Strain_software/Strain_2D-master/example/../Strain_Tools/bin/strain_rate_compute.py", line 11, in <module>
    internal_coordinator.strain_coordinator(MyParams)
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/strain/internal_coordinator.py", line 27, in strain_coordinator
    output_manager.outputs_2d(Ve, Vn, rot, exx, exy, eyy, MyParams, vels, resids)  # 2D grid output format
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/strain/output_manager.py", line 27, in outputs_2d
    ds = Dataset(
         ^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/dataset.py", line 693, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
                                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/dataset.py", line 422, in merge_data_and_coords
    return merge_core(
           ^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/merge.py", line 705, in merge_core
    dims = calculate_dimensions(variables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/variable.py", line 2984, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'x': length 53 on 'x' and length 54 on {'y': 'Ve', 'x': 'Ve'}
```

**Comment by odito2** [comment]
@kmaterna 
'awk' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "D:\Ariel\Phd\Strain_software\Strain_2D-master\Strain_Tools\bin\strain_rate_compute.py", line 11, in <module>
    internal_coordinator.strain_coordinator(MyParams)
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\internal_coordinator.py", line 26, in strain_coordinator
    [Ve, Vn, rot, exx, exy, eyy, vels, resids] = constructed_object.compute(velField)  # computing strain
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\models\strain_gpsgridder.py", line 26, in compute
    [Ve, Vn, rot_grd, exx_grd, exy_grd, eyy_grd] = compute_gpsgridder(myVelfield, self._strain_range,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\models\strain_gpsgridder.py", line 86, in compute_gpsgridder
    xinc = float(subprocess.check_output('gmt grdinfo -M -C '+file1+' | awk \'{print $8}\'', shell=True))  # x-inc
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gmt grdinfo -M -C Output/gpsgridder/nc_u.nc | awk '{print $8}'' returned non-zero exit status 255.

**Comment by odito2** [comment]
@kmaterna 
On Windows, I get the following error:

'awk' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "D:\Ariel\Phd\Strain_software\Strain_2D-master\Strain_Tools\bin\strain_rate_compute.py", line 11, in <module>
    internal_coordinator.strain_coordinator(MyParams)
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\internal_coordinator.py", line 26, in strain_coordinator
    [Ve, Vn, rot, exx, exy, eyy, vels, resids] = constructed_object.compute(velField)  # computing strain
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\models\strain_gpsgridder.py", line 26, in compute
    [Ve, Vn, rot_grd, exx_grd, exy_grd, eyy_grd] = compute_gpsgridder(myVelfield, self._strain_range,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\site-packages\strain\models\strain_gpsgridder.py", line 86, in compute_gpsgridder
    xinc = float(subprocess.check_output('gmt grdinfo -M -C '+file1+' | awk \'{print $8}\'', shell=True))  # x-inc
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Odelya\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gmt grdinfo -M -C Output/gpsgridder/nc_u.nc | awk '{print $8}'' returned non-zero exit status 255.

Can you remove the dependency on awk?

Switching to Linux, delauny works, but when I try to use gpsgridder I get the following error:

Computing strain invariants for 2d dataset.
Traceback (most recent call last):
  File "/mnt/d/Ariel/Phd/Strain_software/Strain_2D-master/example/../Strain_Tools/bin/strain_rate_compute.py", line 11, in <module>
    internal_coordinator.strain_coordinator(MyParams)
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/strain/internal_coordinator.py", line 27, in strain_coordinator
    output_manager.outputs_2d(Ve, Vn, rot, exx, exy, eyy, MyParams, vels, resids)  # 2D grid output format
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/strain/output_manager.py", line 27, in outputs_2d
    ds = Dataset(
         ^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/dataset.py", line 693, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
                                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/dataset.py", line 422, in merge_data_and_coords
    return merge_core(
           ^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/merge.py", line 705, in merge_core
    dims = calculate_dimensions(variables)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/variable.py", line 2984, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'x': length 53 on 'x' and length 54 on {'y': 'Ve', 'x': 'Ve'}

**Comment by ditafaith** [comment]
Hi @odito2, 
You may keep working on Unix-based machines since it is optimal work in this environment.
Actually, I used the earlier version, then there is no issue using all methods.
![output_rows](https://github.com/kmaterna/Strain_2D/assets/126780178/8a70440e-cf19-4822-9b6f-da9e23d50e5c)

**Comment by odito2** [comment]
@kmaterna 
Switching to Linux, delauny works, but when I try to use gpsgridder I get the following error:

Computing strain invariants for 2d dataset.
Traceback (most recent call last):
File "/mnt/d/Ariel/Phd/Strain_software/Strain_2D-master/example/../Strain_Tools/bin/strain_rate_compute.py", line 11, in
internal_coordinator.strain_coordinator(MyParams)
File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/strain/internal_coordinator.py", line 27, in strain_coordinator
output_manager.outputs_2d(Ve, Vn, rot, exx, exy, eyy, MyParams, vels, resids) # 2D grid output format
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/strain/output_manager.py", line 27, in outputs_2d
ds = Dataset(
^^^^^^^^
File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/dataset.py", line 693, in init
variables, coord_names, dims, indexes, _ = merge_data_and_coords(
^^^^^^^^^^^^^^^^^^^^^^
File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/dataset.py", line 422, in merge_data_and_coords
return merge_core(
^^^^^^^^^^^
File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/merge.py", line 705, in merge_core
dims = calculate_dimensions(variables)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/odelya/anaconda3/envs/Strain_2D/lib/python3.12/site-packages/xarray/core/variable.py", line 2984, in calculate_dimensions
raise ValueError(
ValueError: conflicting sizes for dimension 'x': length 53 on 'x' and length 54 on {'y': 'Ve', 'x': 'Ve'}
